import pandas as pd
from pathlib import Path


# ============================================================
# AERIS — HISTORICAL PATTERN EXPLANATION
# ============================================================

INPUT_FILE = Path(
    "data/processed/aeris_risk_predictions.csv"
)

OUTPUT_FILE = Path(
    "data/processed/aeris_historical_patterns.csv"
)


print("=" * 80)
print("AERIS HISTORICAL PATTERN EXPLANATION")
print("=" * 80)


# ============================================================
# LOAD DATA
# ============================================================

print("\nLoading risk predictions...")

if not INPUT_FILE.exists():
    raise FileNotFoundError(
        f"Input file not found: {INPUT_FILE}"
    )

df = pd.read_csv(INPUT_FILE)

print("Input shape:", df.shape)


# ============================================================
# REQUIRED COLUMNS
# ============================================================

REQUIRED_COLUMNS = [
    "Turbine_ID",
    "Timestamp",
    "is_anomaly",
    "persistent_anomaly",
    "strong_persistent_anomaly",
    "power_deviation",
    "Gear_Bear_Temp_Avg",
    "risk_score",
    "risk_level",
]


missing = [
    column
    for column in REQUIRED_COLUMNS
    if column not in df.columns
]

if missing:
    raise ValueError(
        "Missing required columns: "
        + ", ".join(missing)
    )


# ============================================================
# PREPARE DATA
# ============================================================

df["Timestamp"] = pd.to_datetime(
    df["Timestamp"],
    errors="coerce"
)

df = df.dropna(
    subset=[
        "Turbine_ID",
        "Timestamp",
        "risk_score",
        "risk_level",
    ]
).copy()


df = df.sort_values(
    ["Turbine_ID", "Timestamp"]
).reset_index(drop=True)


print("Rows available:", len(df))

print(
    "Turbines:",
    sorted(df["Turbine_ID"].unique())
)


# ============================================================
# DEFINE HISTORICAL RISK CONDITION
# ============================================================

# LOW is not treated as a historical risk event.
#
# MEDIUM and HIGH are treated as risk periods.
#
# This uses the existing risk_level generated by Part 24.

df["risk_event"] = (
    df["risk_level"]
    .astype(str)
    .str.upper()
    .isin(["MEDIUM", "HIGH"])
)


# ============================================================
# IDENTIFY CONTINUOUS RISK PERIODS
# ============================================================

# A new event starts when:
#
# 1. risk_event becomes True
# 2. OR the previous timestamp is not 10 minutes earlier
# 3. OR the previous row belongs to another turbine

time_difference = (
    df.groupby("Turbine_ID")["Timestamp"]
    .diff()
)

previous_risk = (
    df.groupby("Turbine_ID")["risk_event"]
    .shift(1)
)


new_event = (
    df["risk_event"]
    & (
        (~previous_risk.fillna(False))
        | (
            time_difference
            != pd.Timedelta(minutes=10)
        )
    )
)


df["event_id"] = (
    new_event
    .groupby(df["Turbine_ID"])
    .cumsum()
)


risk_rows = df[
    df["risk_event"]
].copy()


# ============================================================
# BUILD HISTORICAL EVENTS
# ============================================================

events = []


for (
    turbine_id,
    event_id
), group in risk_rows.groupby(
    ["Turbine_ID", "event_id"]
):

    group = group.sort_values(
        "Timestamp"
    ).copy()


    # --------------------------------------------------------
    # Basic event information
    # --------------------------------------------------------

    start_time = group["Timestamp"].min()
    end_time = group["Timestamp"].max()

    reading_count = len(group)

    duration_minutes = (
        reading_count * 10
    )


    # --------------------------------------------------------
    # Risk information
    # --------------------------------------------------------

    maximum_risk = float(
        group["risk_score"].max()
    )

    average_risk = float(
        group["risk_score"].mean()
    )


    highest_risk_row = group.loc[
        group["risk_score"].idxmax()
    ]

    highest_risk_level = str(
        highest_risk_row["risk_level"]
    ).upper()


    # --------------------------------------------------------
    # Indicators during event
    # --------------------------------------------------------

    anomaly_detected = bool(
        (group["is_anomaly"] == 1).any()
    )

    persistence_detected = bool(
        (group["persistent_anomaly"] == 1).any()
    )

    strong_persistence_detected = bool(
        (
            group["strong_persistent_anomaly"] == 1
        ).any()
    )


    # --------------------------------------------------------
    # Power deviation
    # --------------------------------------------------------

    power_deviation_max = float(
        group["power_deviation"].max()
    )

    power_deviation_min = float(
        group["power_deviation"].min()
    )

    power_deviation_abs_max = float(
        group["power_deviation"]
        .abs()
        .max()
    )


    # --------------------------------------------------------
    # Temperature
    # --------------------------------------------------------

    maximum_temperature = float(
        group["Gear_Bear_Temp_Avg"].max()
    )


    # --------------------------------------------------------
    # Explanation
    # --------------------------------------------------------

    reasons = []


    if anomaly_detected:
        reasons.append(
            "anomalous operating behaviour"
        )


    if persistence_detected:
        reasons.append(
            "persistent anomaly"
        )


    if strong_persistence_detected:
        reasons.append(
            "strong persistence"
        )


    if power_deviation_abs_max >= 0.05:

        if power_deviation_max >= 0.05:
            reasons.append(
                "positive power deviation"
            )

        if power_deviation_min <= -0.05:
            reasons.append(
                "negative power deviation"
            )


    if maximum_temperature >= 68:

        reasons.append(
            "high gearbox bearing temperature"
        )

    elif maximum_temperature >= 66:

        reasons.append(
            "elevated gearbox bearing temperature"
        )


    if reasons:

        explanation = (
            "Historical risk period associated with "
            + ", ".join(reasons)
            + "."
        )

    else:

        explanation = (
            "Historical medium-risk period detected."
        )


    # --------------------------------------------------------
    # Save event
    # --------------------------------------------------------

    events.append(
        {
            "Turbine_ID": turbine_id,

            "event_start": start_time,

            "event_end": end_time,

            "duration_minutes": duration_minutes,

            "readings": reading_count,

            "highest_risk_level":
                highest_risk_level,

            "maximum_risk_score":
                maximum_risk,

            "average_risk_score":
                average_risk,

            "anomaly_detected":
                int(anomaly_detected),

            "persistent_anomaly_detected":
                int(persistence_detected),

            "strong_persistence_detected":
                int(strong_persistence_detected),

            "maximum_power_deviation":
                power_deviation_max,

            "minimum_power_deviation":
                power_deviation_min,

            "maximum_absolute_power_deviation":
                power_deviation_abs_max,

            "maximum_gear_bearing_temperature":
                maximum_temperature,

            "explanation":
                explanation,
        }
    )


# ============================================================
# CREATE OUTPUT DATAFRAME
# ============================================================

patterns = pd.DataFrame(events)


if patterns.empty:

    print(
        "\nNo MEDIUM or HIGH historical risk periods found."
    )

    patterns = pd.DataFrame(
        columns=[
            "Turbine_ID",
            "event_start",
            "event_end",
            "duration_minutes",
            "readings",
            "highest_risk_level",
            "maximum_risk_score",
            "average_risk_score",
            "anomaly_detected",
            "persistent_anomaly_detected",
            "strong_persistence_detected",
            "maximum_power_deviation",
            "minimum_power_deviation",
            "maximum_absolute_power_deviation",
            "maximum_gear_bearing_temperature",
            "explanation",
        ]
    )


# ============================================================
# SORT EVENTS
# ============================================================

patterns = patterns.sort_values(
    [
        "Turbine_ID",
        "maximum_risk_score",
        "event_start",
    ],
    ascending=[
        True,
        False,
        True,
    ],
).reset_index(drop=True)


# ============================================================
# SAVE
# ============================================================

patterns.to_csv(
    OUTPUT_FILE,
    index=False
)


# ============================================================
# VALIDATION OUTPUT
# ============================================================

print("\nHistorical risk periods:", len(patterns))

print("\nEvents by turbine:")

if not patterns.empty:

    print(
        patterns["Turbine_ID"]
        .value_counts()
        .sort_index()
    )

print("\nHighest-risk historical periods:")

if not patterns.empty:

    display_columns = [
        "Turbine_ID",
        "event_start",
        "event_end",
        "highest_risk_level",
        "maximum_risk_score",
        "maximum_gear_bearing_temperature",
        "explanation",
    ]

    print(
        patterns[
            display_columns
        ]
        .sort_values(
            "maximum_risk_score",
            ascending=False
        )
        .head(20)
        .to_string(index=False)
    )


print("\nSaved:")
print(OUTPUT_FILE)

print("\nOutput shape:")
print(patterns.shape)

print("\nOutput columns:")
print(patterns.columns.tolist())


print("\n" + "=" * 80)
print("HISTORICAL PATTERN EXPLANATION FINISHED")
print("=" * 80)